name: your_clinic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/1_home.png
