// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApISUwghKwbxLzLc2QLDT7pSxmgRETirU',
    appId: '1:761616298792:web:e246926b11aabb3c18961d',
    messagingSenderId: '761616298792',
    projectId: 'yourclinic-9146b',
    authDomain: 'yourclinic-9146b.firebaseapp.com',
    storageBucket: 'yourclinic-9146b.appspot.com',
    measurementId: 'G-N4QKWJ5R14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ZFp2VJDkS3_buz64SZTR6UKsnb3-3Fk',
    appId: '1:761616298792:android:9b1f526debc29a8b18961d',
    messagingSenderId: '761616298792',
    projectId: 'yourclinic-9146b',
    storageBucket: 'yourclinic-9146b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSAjygeOIrUkdmMynzGPKNXrlKQDWO2vA',
    appId: '1:761616298792:ios:46cd27e9898df92b18961d',
    messagingSenderId: '761616298792',
    projectId: 'yourclinic-9146b',
    storageBucket: 'yourclinic-9146b.appspot.com',
    iosBundleId: 'com.example.yourClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSAjygeOIrUkdmMynzGPKNXrlKQDWO2vA',
    appId: '1:761616298792:ios:46cd27e9898df92b18961d',
    messagingSenderId: '761616298792',
    projectId: 'yourclinic-9146b',
    storageBucket: 'yourclinic-9146b.appspot.com',
    iosBundleId: 'com.example.yourClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApISUwghKwbxLzLc2QLDT7pSxmgRETirU',
    appId: '1:761616298792:web:0d33d546949c7f3318961d',
    messagingSenderId: '761616298792',
    projectId: 'yourclinic-9146b',
    authDomain: 'yourclinic-9146b.firebaseapp.com',
    storageBucket: 'yourclinic-9146b.appspot.com',
    measurementId: 'G-Y241TZRQ9Y',
  );
}
